declare module "clean-webpack-plugin";
declare module "connect-history-api-fallback";
declare module "html-webpack-plugin";
declare module "koa-connect";
declare module "mini-css-extract-plugin";
declare module "time-fix-plugin";
declare module "uglifyjs-webpack-plugin";
declare module "webpack-bundle-analyzer";
declare module "webpack-node-externals";
