target = "web"
entry = "client/index.ts"
namespace = "@web"
loaders = ["css", "stylus", "typescript"]
[alias]
joi = "joi-browser"
[plugins.html]
title = "Web"
[serve]
host = "0.0.0.0"
[serve.hot]
serverHost = "0.0.0.0"
clientHost = "localhost"
