# What to target (Web in this example)
target = "web"

# Entry
entry = "client/index.ts"

# Namespace of the project (For aliases)
namespace = "@web"

# Loaders to use
loaders = ["css", "stylus", "typescript"]

# List of module aliases
[alias]
joi = "joi-browser"

[plugins.clean]
# paths = ["some/path"] # Paths that need to be cleaned up by the clean plugin (In addition to public/assets)
# exclude = ["some", "file"] # Files ignored by the cleanup (In all directories)

# Html plugin parameters
[plugins.html]
title = "Web" # Title (- Dev will be added when in development mode)

# webpack-serve configuration (Only for web targets)
[serve]
# port = 8080 # Bind port (Default 8080)
host = "0.0.0.0" # Bind host (Default 127.0.0.1)
# content = ["some/directory"] # Directories to serve as static content (In addition to public)

# webpack-hot-client
[serve.hot]
# port = 8081 # Bind port (Default 8081)
serverHost = "0.0.0.0" # Specific server-side host
clientHost = "localhost" # Specific client-side host (Where the websocket should make requests)
# host = "127.0.0.1" # Host on both sides (Default 127.0.0.1)
